### ISSUE TITLE
Not Supporting laravel/framework v8

### ISSUE THREAD

**Issue by dhruva81** [ZsgsDesign/laravel-pdf-latex#10]
Hi.. This is not supporting laravel v8 :(

**Comment by dhruva81** [comment]
Hi @ZsgsDesign 
This version of laravel-pdf-latex is not supporting laravel 8.x

**Comment by ZsgsDesign** [comment]
ok @dhruva81

**Comment by dhruva81** [comment]
Hi @ZsgsDesign 
If possible, kindly upgrade it to support Laravel 8.x.
My educational website is build on version 8. 
And I need this package to create maths and science worksheets for students.
Please...
Thanks
