### ISSUE TITLE
Error - Unsupported Operating System 

### ISSUE THREAD

**Issue by dhruva81** [ZsgsDesign/laravel-pdf-latex#5]
ZsgsDesign\PDFConverter\LatextException
Unsupported Operating System 

I am getting this error. Please guide me

**Comment by datapoesy** [comment]
ZsgsDesign\PDFConverter\LatextException
Unsupported Operating System
I am also getting the same error. Not sure whether this is not meant for windows.  I use it on Windows 10.

**Comment by ZsgsDesign** [comment]
It supports only Linux. You can use it with WSL2 on Win10.
